Calibration files set up
ImperialCollegeLondon/bubble_analyser pull request #37
Opened 2024-07-12 02:21 UTC by gyyyno1

# Description

Added calibration files. Renamed sample images and calibration files. Moved them to "tests".

Fixes #33 #34 #35 #36 #29 

## Type of change

- [ ] Documentation (non-breaking change that adds or improves the documentation)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Key checklist

- [ ] All tests pass (eg. `python -m pytest`)
- [ ] The documentation builds and looks OK (eg. `python -m sphinx -b html docs docs/build`)
- [x] Pre-commit hooks run successfully (eg. `pre-commit run --all-files`)

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added or an issue has been opened to tackle that in the future. (Indicate issue here: # (issue))

2024-07-15 09:04 UTC, dalonsoa requested changes
Made a small request, but otherwise this change looks sensible. 

I would suggest to rename files with double digits, and lowercase extension, so sorting is consistent, eg. `01.jpg`, `02.jpg`, etc.

2024-07-15 09:04 UTC, dalonsoa commented on tests/calibration_files/Calibration.csv
What is this file for? I think it might make more sense to use TOML here as it is about describing different parameters information, not an actual table of data, which is what CSV format is for.

```toml
[image_resolution]
value = 183.06589
units = "px/mm"
```

2024-07-15 09:18 UTC, dmesa16 commented on tests/calibration_files/Calibration.csv
it is just a registry of the options the user chose for that particular set of photos. It results from the UI process (i.e., selecting the image with the ruler and marking the two dots 1 cm apart to calibrate the px/mm). I'm happy to be saved in any readable format, as it is just a registry

2024-07-15 09:23 UTC, dalonsoa commented on tests/calibration_files/Calibration.csv
Yeah, I thought to. For that sort of settings, configuration and the sort, things like TOML or YAML are a more readable option - and structurally more sound since options are not really tabular data, even if they have the same fields. The above TOML code will load as a nested dictionary in `python`, so very easy to access the options, equivalent to:

```python
config = {"image_resolution": {"value": 183.06589, "units": "px/mm"}}
```

2024-07-17 07:50 UTC, gyyyno1 commented on tests/calibration_files/Calibration.csv
> Yeah, I thought to. For that sort of settings, configuration and the sort, things like TOML or YAML are a more readable option - and structurally more sound since options are not really tabular data, even if they have the same fields. The above TOML code will load as a nested dictionary in `python`, so very easy to access the options, equivalent to:
> 
> ```python
> config = {"image_resolution": {"value": 183.06589, "units": "px/mm"}}
> ```

So shall I create a toml file for this registry? As Dr Mesa said this is a registry file from the UI process, I guess it's more reasonable to modify the coding that generating this registry instead of directly creating a new toml config file?

2024-07-17 08:00 UTC, dalonsoa commented on tests/calibration_files/Calibration.csv
Even if it is generated by the UI in the long run, you still want to load it with the right tools when you start writing code, and that means it should have the right format from the beginning. So, yes, replace the `Calibration.csv` file with a `calibration.toml` file and the contents above.

2024-07-17 08:02 UTC, dmesa16 commented on tests/calibration_files/Calibration.csv
Exactly. The Python code should be modified so it outputs a .toml or .yml file after the user clicks next in the second tab.

So far, the flow is: the first tab is folder selection, the second tab is size calibration and background removal, and the third one is for algorithm selection, parameter modification and visually checking the result on one photo. After clicking next here, the program properly runs, analysing all the photos from the folder selected in step 1, removing the background chosen in step 2 and using the segmentation algorithm chosen in step 3. The fourth tab simply displays the results and some statistics.

2024-07-17 08:16 UTC, gyyyno1 commented on tests/calibration_files/Calibration.csv
> Exactly. The Python code should be modified so it outputs a .toml or .yml file after the user clicks next in the second tab.
> 
> So far, the flow is: the first tab is folder selection, the second tab is size calibration and background removal, and the third one is for algorithm selection, parameter modification and visually checking the result on one photo. After clicking next here, the program properly runs, analysing all the photos from the folder selected in step 1, removing the background chosen in step 2 and using the segmentation algorithm chosen in step 3. The fourth tab simply displays the results and some statistics.
> 
> I am completely open to suggestions if you think there is a better flow or intermediate step that may work better :)


Based on both of your suggestions, I replaced the csv file with a new toml file, and I will keep an eye on the code modification for the registry generation in the future as well.

2024-07-18 12:06 UTC, dalonsoa approved these changes

2024-07-18 12:06 UTC, merged